version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      disable:
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/pinotelio/terraform-provider-n8n
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
